name: pifold_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aria2=1.37.0=h4e1c2bf_3
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - foldseek=10.941cd33=h5021889_1
  - gawk=5.3.1=hcd3d067_0
  - gmp=6.3.0=hac33072_2
  - icu=73.2=h59595ed_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libasprintf=0.25.1=h3f43e3d_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - mpfr=4.2.1=h90cbb55_3
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.1=h35e630c_1
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bitsandbytes==0.45.5
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.1.8
      - datasets==3.1.0
      - dill==0.3.8
      - docstring-parser==0.17.0
      - eval-type-backport==0.3.1
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - hf-xet==1.2.0
      - huggingface-hub==0.36.1
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mini3di==0.2.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==26.0
      - pandas==2.0.3
      - peft==0.13.2
      - platformdirs==4.3.6
      - propcache==0.2.0
      - protobuf==5.29.6
      - psutil==7.2.2
      - pyarrow==17.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.3.2
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentry-sdk==2.53.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tokenizers==0.20.3
      - torch==2.4.1
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu121
      - tqdm==4.67.3
      - transformers==4.46.3
      - triton==3.0.0
      - trl==0.11.4
      - typeguard==4.4.0
      - typing-extensions==4.13.2
      - tyro==1.0.6
      - tzdata==2025.3
      - urllib3==2.2.3
      - wandb==0.24.2
      - xxhash==3.6.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/ou222/miniconda3/envs/pifold
