name: pifold_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - aria2=1.37.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates
  - foldseek
  - gawk=5.3.1
  - gmp=6.3.0
  - icu=73.2
  - libffi=3.4.4
  - libgcc-ng
  - libgomp
  - libiconv=1.18
  - libsqlite
  - libssh2=1.11.1
  - libstdcxx-ng
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - openssl
  - readline=8.3
  - sqlite
  - tk=8.6.15
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.4.1+cu121.html
    - accelerate==1.0.1
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - bitsandbytes==0.45.5
    - certifi
    - charset-normalizer==3.4.4
    - click==8.1.8
    - datasets==3.1.0
    - dill==0.3.8
    - docstring-parser==0.17.0
    - eval-type-backport==0.3.1
    - filelock==3.16.1
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gitdb==4.0.12
    - gitpython==3.1.46
    - hf-xet==1.2.0
    - huggingface-hub==0.36.1
    - idna==3.11
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - jinja2==3.1.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - mdurl==0.1.2
    - mini3di==0.2.1
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - networkx==3.1
    - numpy==1.23.5
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - packaging==26.0
    - pandas==2.0.3
    - peft==0.13.2
    - platformdirs==4.3.6
    - propcache==0.2.0
    - protobuf==5.29.6
    - psutil==7.2.2
    - pyarrow==17.0.0
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.19.2
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - regex==2024.11.6
    - requests==2.32.4
    - rich==14.3.2
    - safetensors==0.5.3
    - scipy==1.10.1
    - sentry-sdk==2.53.0
    - six==1.17.0
    - smmap==5.0.2
    - sympy==1.13.3
    - tokenizers==0.20.3
    - torch==2.4.1
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2
    - tqdm==4.67.3
    - transformers==4.46.3
    - triton==3.0.0
    - trl==0.11.4
    - typeguard==4.4.0
    - typing-extensions==4.13.2
    - tyro==1.0.6
    - tzdata==2025.3
    - urllib3==2.2.3
    - wandb==0.24.2
    - xxhash==3.6.0
    - yarl==1.15.2
    - zipp==3.20.2
